# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD Test

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false  # true시 warning까지 에러로 출력

    # Nodejs 런타임 정보 설정  
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: 1. Checkout source code.   # Repo checkout
        uses: actions/checkout@v2
      
      - name: 2. Check Node v            # Node v 확인
        run: node -v

      - name: 캐시 지우기
        run: |
          yarn cache clean
          rm -rf node_modules
          rm -rf package-lock.json
          rm -rf yarn.lock

      - name: 3. Install     
        run: yarn

      - name: 4. Build                   # React Build
        run: yarn build

      - name: 5. Deploy                  # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://4tar1p-frontend-github-actions-s3-bucket

      # 업로드한 s3 파일을 각 CDN 캐시 무효화하여 리프레시 하기
      - name: 6. CloudFront Invalidation
        env:
          AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID}}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $AWS_CLOUDFRONT_ID --paths "/*" 
