# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD Test

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false  # true시 warning까지 에러로 출력

    # Nodejs 런타임 정보 설정  
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: 1. Checkout source code.   # Repo checkout
        uses: actions/checkout@v2
      
      - name: 2. Check Node v            # Node v 확인
        run: node -v

      - name: 3. Install Dependencies    # 의존 파일 설치
        run: yarn install --frozen-lockfile

      - name: 4. Build                   # React Build
        run: yarn build

      - name: Deploy                  # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://4tar1p-frontend-github-actions-s3-bucket